### User sing up endpoint
 POST http://localhost:3001/v1/user
 Content-Type: application/json

    {
    "name":"Nitin",
    "branch":"Computer engineering",
    "rollno":"22240",
    "year":"Second Year",
    "address":"Pune",
    "phoneno":"7841983996",
    "email":"Nitin@gmail.com",
    "password":"@Nitin123"
}

### User sing in endpoint
 POST http://localhost:3001/v1/user/login
 Content-Type: application/json

    {
    "email":"Nitin@gmail.com",
    "password":"@Nitin123"
}
 